version: '3.8'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
      POSTGRES_USER: postgres
    volumes:
      - ./docker/database-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 5432
        protocol: tcp
  adminer:
    image: adminer
    ports:
      - "8089:8080"
    depends_on:
      - db

  redis:
    image: redis:alpine
    command: redis-server /usr/local/etc/redis/redis.conf --requirepass mypassword
    ports:
      - "6379:6379"
    volumes:
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf


volumes:
  database-data: {}